sync main repo build.yml
to enable manual workflow button

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,6 +1,6 @@
 name: Build
 
-on: [push]
+on: [push ,workflow_dispatch]
 
 jobs:
   build:
@@ -8,17 +8,22 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v4
+
+    - name: Confirm Saxon CLI class is in the JAR
+      run: jar tf utilities/saxon9he/saxon9he.jar | grep net/sf/saxon/Transform.class || echo "Transform.class not found"
 
     - name: Set up JDK 1.8
-      uses: actions/setup-java@v1
+      uses: actions/setup-java@v4
       with:
-        java-version: 1.8
+        distribution: 'zulu'
+        java-version: 8
+        java-package: jdk
 
     - name: Dependencies
       run: |
         sudo apt update
-        sudo apt install -y aspell libreoffice
+        sudo apt install -y aspell libreoffice pandoc
 
     - name: Build
       env:
@@ -30,7 +35,52 @@ jobs:
         echo "TIMESTAMP=${timestamp}" >>$GITHUB_ENV
         bash build.sh target github ${timestamp}z "${REALTA_USERNAME:-}" "${REALTA_PASSWORD:-}" DELETE-REPOSITORY-FILES-AS-WELL
 
-    - uses: actions/upload-artifact@v2
+    - uses: actions/upload-artifact@v4
+      with:
+        name: UBL-package-github-${{ env.TIMESTAMP }}z
+        path: ./*
+        #path: target/artefacts-UBL-2.3-github-${{ env.TIMESTAMP }}z/*
+        #name: all-UBL-2.3-github-${{ env.TIMESTAMP }}z
+        #path: ./*
+
+  build-py:
+    if: github.ref == 'refs/heads/ubl-2.5-python'
+    runs-on: ubuntu-latest
+
+    steps:
+    - uses: actions/checkout@v4
+
+    - name: Confirm Saxon CLI class is in the JAR
+      run: jar tf utilities/saxon9he/saxon9he.jar | grep net/sf/saxon/Transform.class || echo "Transform.class not found"
+
+    - name: Set up JDK 1.8
+      uses: actions/setup-java@v4
+      with:
+        distribution: 'zulu'
+        java-version: 8
+        java-package: jdk
+
+    - name: Set up Python
+      uses: actions/setup-python@v4
+      with:
+        python-version: '3.12' 
+
+    - name: Dependencies
+      run: |
+        sudo apt update
+        sudo apt install -y aspell libreoffice pandoc
+
+    - name: Build
+      env:
+        REALTA_USERNAME: ${{ secrets.REALTA_USERNAME }}
+        REALTA_PASSWORD: ${{ secrets.REALTA_PASSWORD }}
+      run: |
+        mkdir target-py
+        timestamp=$(date -u +%Y%m%d-%H%M)
+        echo "TIMESTAMP=${timestamp}" >>$GITHUB_ENV
+        python build.py target-py github ${timestamp}z "${REALTA_USERNAME:-}" "${REALTA_PASSWORD:-}" DELETE-REPOSITORY-FILES-AS-WELL
+
+    - uses: actions/upload-artifact@v4
       with:
         name: UBL-package-github-${{ env.TIMESTAMP }}z
         path: ./*
